imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        #resources: ['bootstrap_3_layout.html.twig']
        resources: ['bootstrap_3_horizontal_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ APPMaldabaBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            # the path to the uglifyjs executable
            #bin: /usr/local/bin/uglifyjs
            apply_to: "\.js$"
            bin: "%kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs"
        uglifycss:
            #bin: /usr/local/bin/uglifycss
            apply_to: "\.css$"
            bin: "%kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:   "%database_driver_default%"
                host:     "%database_host_default%"
                port:     "%database_port_default%"
                dbname:   "%database_name_default%"
                user:     "%database_user_default%"
                password: "%database_password_default%"
                charset:  UTF8

    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    APPMaldabaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Gedmo settings
stof_doctrine_extensions:        
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            timestampable: true
            translatable: true
            sluggable: true
            loggable: true