<?php

namespace APP\MaldabaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAddressRepository extends EntityRepository
{
}
